[package]
name = "kommandozeilen_argumente_derive"
version = "0.3.0"
description = "derive-Macros für das kommandozeilen_argumente crate."
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
litrs = "0.4.1"
proc-macro2 = "1.0.36"
quote = "1.0.17"
unicode-segmentation = "1.9.0"
venial = "0.6.0"

[lints]
workspace = true
